# Please do have a look into the Exploratory Data analysis file before looking into the below code for your understanding the data set

In [2]:
# import all the needed libraries for Simple Linear Regression Model

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import pickle
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

# STEP1:(Data Collection)Importing data set from the location

In [3]:


Data = pd.read_csv(r"C:\Users\Vinoth\Desktop\HOPE AI\Machine Learning\Simple Linear Regression\DataSet\tvmarketing.csv")

In [4]:
Data.head()

TV  Sales
0  230.1   22.1
1   44.5   10.4
2   17.2    9.3
3  151.5   18.5
4  180.8   12.9

# STEP 2 : (Data Preprocessing)
## -->As you have seen the Exploratory Data Analysis file that there is no null or NA values in data set
## -->The input has only one columns so we don't need to check for feature/column selection 

# STEP 3 : INPUT(Dependent Variable) and Output(Independent Variable split)

In [5]:
independent = Data[["TV"]]
dependent = Data[["Sales"]]

In [6]:
independent

TV
0    230.1
1     44.5
2     17.2
3    151.5
4    180.8
..     ...
195   38.2
196   94.2
197  177.0
198  283.6
199  232.1

[200 rows x 1 columns]

In [7]:
dependent

Sales
0     22.1
1     10.4
2      9.3
3     18.5
4     12.9
..     ...
195    7.6
196    9.7
197   12.8
198   25.5
199   13.4

[200 rows x 1 columns]

# STEP 4: Train and Test Data Splitting

In [8]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(independent, dependent, test_size=0.30,random_state=0)

In [9]:
X_train.shape

(140, 1)

In [12]:
y_train.shape

(140, 1)

# STEP 5: Built/Train the model using the Training Data

In [14]:
Linear_Model = LinearRegression()
Linear_Model.fit(X_train,y_train)

LinearRegression()

# from the linear equation of y=mx+c the below is the slope m value that is fitted for all the training data points which is refered as weight w 

In [26]:


weight=Linear_Model.coef_
weight

array([[0.04581434]])

# from the linear equation of y=mx+c the below is the intercept c value that is fitted for all the training data points which is refered as bias c 

In [18]:
# from the linear equation of y=mx+c the below is the c value w
bais=Linear_Model.intercept_
bais

array([7.31081017])

# STEP 6: Test your model with test data points that we have seperated from the total data set using train_test_split

In [ ]:
y_pred=Linear_Model.predict(X_test)
y_pred

# STEP 7: Validate the accuracy of your model prediction from the actual output expected against the model predicted output

## Below we use r2_score as our accuracy score for the model but it changes based on the each model

In [32]:
from sklearn.metrics import r2_score

In [33]:
r_score=r2_score(y_test,y_pred)

In [34]:
r_score

0.725606346597073

# Observation : from the above output we got to know that our model predicts the output values with 72% of accuracy with our test data

# STEP 8 : save the model using pickle functions so that we can use it for further deployment stage to load only the model parameters

In [36]:
import pickle

In [39]:
pickle.dump(Linear_Model,open("Linear_regression_final_model.sav",'wb'))

# We can load the saved model and test it if it works

In [43]:
loaded_model=pickle.load(open("Linear_regression_final_model.sav",'rb'))
output=loaded_model.predict([[300]])

C:\Users\Vinoth\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


In [45]:
output

array([[21.05511282]])

# STEP 9 : Now if clients are okay with the accuracy parameters and everything looks good we can now create app and deploy this code to production environment